errors module
-------------

.. automodule:: datumaro.cli.util.errors

   .. autoclass:: CliException
      :members:
      :private-members:
      :show-inheritance:

   .. autoclass:: WrongRevpathError
      :members:
      :private-members:
      :show-inheritance:

         .. py:data:: problems = attrib()
