Running Sphinx v5.3.0
loading pickled environment... done
myst v1.0.0: MdParserConfig(commonmark_only=False, gfm_only=False, enable_extensions=set(), disable_syntax=[], all_links_external=False, url_schemes=('http', 'https', 'mailto', 'ftp'), ref_domains=None, fence_as_directive=set(), number_code_blocks=[], title_to_header=False, heading_anchors=0, heading_slug_func=None, html_meta={}, footnote_transition=True, words_per_minute=200, substitutions={}, linkify_fuzzy_links=True, dmath_allow_labels=True, dmath_allow_space=True, dmath_allow_digits=True, dmath_double_inline=False, update_mathjax=True, mathjax_classes='tex2jax_process|mathjax_process|math|output_area', enable_checkboxes=False, suppress_warnings=[], highlight_code_blocks=True)
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: 0 added, 10 changed, 0 removed
reading sources... [ 10%] docs/reference/components/components/datumaro.components.annotation
reading sources... [ 20%] docs/reference/components/components/datumaro.components.converter
reading sources... [ 30%] docs/reference/components/components/datumaro.components.dataset_filter
reading sources... [ 40%] docs/reference/components/components/datumaro.components.extractor
reading sources... [ 50%] docs/reference/components/components/datumaro.components.operations
reading sources... [ 60%] docs/reference/plugins/accuracy_checker_plugin/datumaro.plugins.accuracy_checker_plugin.ac_launcher
reading sources... [ 70%] docs/reference/plugins/accuracy_checker_plugin/details/datumaro.plugins.accuracy_checker_plugin.details.ac
reading sources... [ 80%] docs/reference/plugins/accuracy_checker_plugin/details/datumaro.plugins.accuracy_checker_plugin.details.representation
reading sources... [ 90%] docs/reference/plugins/accuracy_checker_plugin/details/details
reading sources... [100%] docs/reference/plugins/data_formats/datumaro.plugins.data_formats.mot

/home/chuneuny/miniconda3/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.8) or chardet (5.1.0)/charset_normalizer (2.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
WARNING: autodoc: failed to import class 'Category' from module 'datumaro.components.annotation'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.annotation' has no attribute 'Category'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Category

WARNING: autodoc: failed to import class 'Visibility' from module 'datumaro.components.annotation'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.annotation' has no attribute 'Visibility'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: Visibility

WARNING: autodoc: failed to import module 'converter' from module 'datumaro.components'; the following exception was raised:
No module named 'datumaro.components.converter'
WARNING: autodoc: failed to import module 'dataset_filter' from module 'datumaro.components'; the following exception was raised:
No module named 'datumaro.components.dataset_filter'
WARNING: autodoc: failed to import module 'extractor' from module 'datumaro.components'; the following exception was raised:
No module named 'datumaro.components.extractor'
WARNING: autodoc: failed to import function 'get_ann_type' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'get_ann_type'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: get_ann_type

WARNING: autodoc: failed to import function 'match_annotations_equal' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'match_annotations_equal'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: match_annotations_equal

WARNING: autodoc: failed to import function 'merge_annotations_equal' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'merge_annotations_equal'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: merge_annotations_equal

WARNING: autodoc: failed to import function 'merge_categories' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'merge_categories'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: merge_categories

WARNING: autodoc: failed to import class 'MergingStrategy' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'MergingStrategy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: MergingStrategy

WARNING: autodoc: failed to import method 'ExactMerge.merge_items' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'ExactMerge' has no attribute 'merge_items'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: merge_items

WARNING: autodoc: failed to import method 'ExactMerge.merge_images' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'ExactMerge' has no attribute 'merge_images'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: merge_images

WARNING: autodoc: failed to import method 'ExactMerge.merge_anno' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: type object 'ExactMerge' has no attribute 'merge_anno'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: merge_anno

/local/chuneuny/github/datumaro/datumaro/components/operations.py:docstring of datumaro.components.operations.ExactMerge.merge:1: WARNING: duplicate object description of datumaro.components.operations.ExactMerge.merge, other instance in docs/reference/components/components/datumaro.components.operations, use :noindex: for one of them
WARNING: invalid signature for autoclass ('Conf\n.. py:data:: pairwise_dist = attrib(converter=float, default=0.5)\n               sigma = attrib(converter=list, factory=list)')
WARNING: don't know which module to import for autodocumenting 'Conf\n.. py:data:: pairwise_dist = attrib(converter=float, default=0.5)\n               sigma = attrib(converter=list, factory=list)' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
WARNING: autodoc: failed to import function 'get_ann_source' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'get_ann_source'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: get_ann_source

WARNING: autodoc: failed to import function 'merge_items' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'merge_items'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: merge_items

WARNING: autodoc: failed to import function 'merge_annotations' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'merge_annotations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: merge_annotations

WARNING: autodoc: failed to import function 'match_items' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'match_items'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: match_items

/local/chuneuny/github/datumaro/datumaro/components/operations.py:docstring of datumaro.components.operations.IntersectMerge.add_item_error:1: WARNING: duplicate object description of datumaro.components.operations.IntersectMerge.add_item_error, other instance in docs/reference/components/components/datumaro.components.operations, use :noindex: for one of them
WARNING: autodoc: failed to import function 'match_annotations' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'match_annotations'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: match_annotations

WARNING: autodoc: failed to import function 'distance' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'distance'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: distance

WARNING: autodoc: failed to import function 'label_matcher' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'label_matcher'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: label_matcher

WARNING: autodoc: failed to import class 'StatsCounter' from module 'datumaro.components.operations'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.components.operations' has no attribute 'StatsCounter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: StatsCounter

WARNING: autodoc: failed to import module 'ac_launcher' from module 'datumaro.plugins.accuracy_checker_plugin'; the following exception was raised:
No module named 'accuracy_checker'
WARNING: autodoc: failed to import module 'ac' from module 'datumaro.plugins.accuracy_checker_plugin.details'; the following exception was raised:
No module named 'accuracy_checker'
WARNING: autodoc: failed to import module 'representation' from module 'datumaro.plugins.accuracy_checker_plugin.details'; the following exception was raised:
No module named 'accuracy_checker'
WARNING: autodoc: failed to import class 'MotSeqExtractor' from module 'datumaro.plugins.data_formats.mot'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.plugins.data_formats.mot' has no attribute 'MotSeqExtractor'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: MotSeqExtractor

WARNING: autodoc: failed to import class 'MotSeqGtConverter' from module 'datumaro.plugins.data_formats.mot'; the following exception was raised:
Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 376, in safe_getattr
    return getattr(obj, name, *defargs)
AttributeError: module 'datumaro.plugins.data_formats.mot' has no attribute 'MotSeqGtConverter'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/importer.py", line 98, in import_object
    obj = attrgetter(obj, mangled_name)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 306, in get_attr
    return autodoc_attrgetter(self.env.app, obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 2804, in autodoc_attrgetter
    return safe_getattr(obj, name, *defargs)
  File "/home/chuneuny/miniconda3/lib/python3.8/site-packages/sphinx/util/inspect.py", line 392, in safe_getattr
    raise AttributeError(name) from exc
AttributeError: MotSeqGtConverter

looking for now-outdated files... none found
pickling environment... done
checking consistency... /local/chuneuny/github/datumaro/docs/source/docs/explanation/formats/yolo_ultralytics.md: WARNING: document isn't included in any toctree
/local/chuneuny/github/datumaro/docs/source/docs/reference/jupyter_notebook_examples/generate.rst: WARNING: document isn't included in any toctree
/local/chuneuny/github/datumaro/docs/source/docs/reference/jupyter_notebook_examples/validate.rst: WARNING: document isn't included in any toctree
/local/chuneuny/github/datumaro/docs/source/docs/user-manual/command-reference/searcher.md: WARNING: document isn't included in any toctree
done
preparing documents... done
writing output... [  7%] docs/reference/components/components
writing output... [ 14%] docs/reference/components/components/datumaro.components.annotation
writing output... [ 21%] docs/reference/components/components/datumaro.components.converter
writing output... [ 28%] docs/reference/components/components/datumaro.components.dataset_filter
writing output... [ 35%] docs/reference/components/components/datumaro.components.extractor
writing output... [ 42%] docs/reference/components/components/datumaro.components.operations
writing output... [ 50%] docs/reference/plugins/accuracy_checker_plugin/accuracy_checker_plugin
writing output... [ 57%] docs/reference/plugins/accuracy_checker_plugin/datumaro.plugins.accuracy_checker_plugin.ac_launcher
writing output... [ 64%] docs/reference/plugins/accuracy_checker_plugin/details/datumaro.plugins.accuracy_checker_plugin.details.ac
writing output... [ 71%] docs/reference/plugins/accuracy_checker_plugin/details/datumaro.plugins.accuracy_checker_plugin.details.representation
writing output... [ 78%] docs/reference/plugins/accuracy_checker_plugin/details/details
writing output... [ 85%] docs/reference/plugins/data_formats/data_formats
writing output... [ 92%] docs/reference/plugins/data_formats/datumaro.plugins.data_formats.mot
writing output... [100%] index

/local/chuneuny/github/datumaro/datumaro/components/annotation.py:docstring of datumaro.components.annotation.PointsCategories:1: WARNING: more than one target found for cross-reference 'Category': datumaro.components.annotation.LabelCategories.Category, datumaro.components.annotation.PointsCategories.Category
generating indices... genindex py-modindex done
highlighting module code... [  0%] datumaro.cli.util
highlighting module code... [  1%] datumaro.cli.util.errors
highlighting module code... [  2%] datumaro.cli.util.project
highlighting module code... [  3%] datumaro.components.algorithms.rise
highlighting module code... [  4%] datumaro.components.annotation
highlighting module code... [  5%] datumaro.components.cli_plugin
highlighting module code... [  6%] datumaro.components.config
highlighting module code... [  7%] datumaro.components.config_model
highlighting module code... [  8%] datumaro.components.dataset
highlighting module code... [  9%] datumaro.components.dataset_base
highlighting module code... [ 10%] datumaro.components.environment
highlighting module code... [ 11%] datumaro.components.errors
highlighting module code... [ 12%] datumaro.components.extractor_tfds
highlighting module code... [ 13%] datumaro.components.format_detection
highlighting module code... [ 14%] datumaro.components.hl_ops
highlighting module code... [ 15%] datumaro.components.launcher
highlighting module code... [ 16%] datumaro.components.media
highlighting module code... [ 17%] datumaro.components.media_manager
highlighting module code... [ 18%] datumaro.components.operations
highlighting module code... [ 19%] datumaro.components.progress_reporting
highlighting module code... [ 20%] datumaro.components.project
highlighting module code... [ 21%] datumaro.components.validator
highlighting module code... [ 22%] datumaro.plugins.data_formats.ade20k2017
highlighting module code... [ 23%] datumaro.plugins.data_formats.ade20k2020
highlighting module code... [ 24%] datumaro.plugins.data_formats.camvid
highlighting module code... [ 25%] datumaro.plugins.data_formats.cifar
highlighting module code... [ 26%] datumaro.plugins.data_formats.cityscapes
highlighting module code... [ 27%] datumaro.plugins.data_formats.coco.base
highlighting module code... [ 28%] datumaro.plugins.data_formats.coco.exporter
highlighting module code... [ 29%] datumaro.plugins.data_formats.coco.format
highlighting module code... [ 30%] datumaro.plugins.data_formats.coco.importer
highlighting module code... [ 31%] datumaro.plugins.data_formats.cvat.base
highlighting module code... [ 32%] datumaro.plugins.data_formats.cvat.exporter
highlighting module code... [ 33%] datumaro.plugins.data_formats.cvat.format
highlighting module code... [ 34%] datumaro.plugins.data_formats.datumaro.base
highlighting module code... [ 35%] datumaro.plugins.data_formats.datumaro.exporter
highlighting module code... [ 36%] datumaro.plugins.data_formats.datumaro.format
highlighting module code... [ 37%] datumaro.plugins.data_formats.icdar.base
highlighting module code... [ 38%] datumaro.plugins.data_formats.icdar.exporter
highlighting module code... [ 39%] datumaro.plugins.data_formats.icdar.format
highlighting module code... [ 40%] datumaro.plugins.data_formats.image_dir
highlighting module code... [ 41%] datumaro.plugins.data_formats.image_zip
highlighting module code... [ 42%] datumaro.plugins.data_formats.imagenet
highlighting module code... [ 43%] datumaro.plugins.data_formats.imagenet_txt
highlighting module code... [ 44%] datumaro.plugins.data_formats.kitti.base
highlighting module code... [ 45%] datumaro.plugins.data_formats.kitti.exporter
highlighting module code... [ 46%] datumaro.plugins.data_formats.kitti.format
highlighting module code... [ 47%] datumaro.plugins.data_formats.kitti.importer
highlighting module code... [ 48%] datumaro.plugins.data_formats.kitti_raw.base
highlighting module code... [ 49%] datumaro.plugins.data_formats.kitti_raw.exporter
highlighting module code... [ 50%] datumaro.plugins.data_formats.kitti_raw.format
highlighting module code... [ 50%] datumaro.plugins.data_formats.labelme
highlighting module code... [ 51%] datumaro.plugins.data_formats.lfw
highlighting module code... [ 52%] datumaro.plugins.data_formats.market1501
highlighting module code... [ 53%] datumaro.plugins.data_formats.mnist
highlighting module code... [ 54%] datumaro.plugins.data_formats.mnist_csv
highlighting module code... [ 55%] datumaro.plugins.data_formats.mot
highlighting module code... [ 56%] datumaro.plugins.data_formats.mots
highlighting module code... [ 57%] datumaro.plugins.data_formats.open_images
highlighting module code... [ 58%] datumaro.plugins.data_formats.sly_pointcloud.base
highlighting module code... [ 59%] datumaro.plugins.data_formats.sly_pointcloud.exporter
highlighting module code... [ 60%] datumaro.plugins.data_formats.sly_pointcloud.format
highlighting module code... [ 61%] datumaro.plugins.data_formats.tf_detection_api.base
highlighting module code... [ 62%] datumaro.plugins.data_formats.tf_detection_api.exporter
highlighting module code... [ 63%] datumaro.plugins.data_formats.tf_detection_api.format
highlighting module code... [ 64%] datumaro.plugins.data_formats.vgg_face2
highlighting module code... [ 65%] datumaro.plugins.data_formats.voc.base
highlighting module code... [ 66%] datumaro.plugins.data_formats.voc.exporter
highlighting module code... [ 67%] datumaro.plugins.data_formats.voc.format
highlighting module code... [ 68%] datumaro.plugins.data_formats.voc.importer
highlighting module code... [ 69%] datumaro.plugins.data_formats.widerface
highlighting module code... [ 70%] datumaro.plugins.data_formats.yolo.base
highlighting module code... [ 71%] datumaro.plugins.data_formats.yolo.exporter
highlighting module code... [ 72%] datumaro.plugins.data_formats.yolo.format
highlighting module code... [ 73%] datumaro.plugins.ndr
highlighting module code... [ 74%] datumaro.plugins.openvino_plugin.launcher
highlighting module code... [ 75%] datumaro.plugins.openvino_plugin.samples.mobilenet_v2_pytorch_interp
highlighting module code... [ 76%] datumaro.plugins.openvino_plugin.samples.ssd_face_detection_interp
highlighting module code... [ 77%] datumaro.plugins.openvino_plugin.samples.ssd_mobilenet_coco_detection_interp
highlighting module code... [ 78%] datumaro.plugins.openvino_plugin.samples.ssd_person_detection_interp
highlighting module code... [ 79%] datumaro.plugins.openvino_plugin.samples.ssd_person_vehicle_bike_detection_interp
highlighting module code... [ 80%] datumaro.plugins.openvino_plugin.samples.ssd_vehicle_detection_interp
highlighting module code... [ 81%] datumaro.plugins.sampler.algorithm.algorithm
highlighting module code... [ 82%] datumaro.plugins.sampler.algorithm.entropy
highlighting module code... [ 83%] datumaro.plugins.sampler.random_sampler
highlighting module code... [ 84%] datumaro.plugins.sampler.relevancy_sampler
highlighting module code... [ 85%] datumaro.plugins.splitter
highlighting module code... [ 86%] datumaro.plugins.tiling.tile
highlighting module code... [ 87%] datumaro.plugins.transforms
highlighting module code... [ 88%] datumaro.plugins.validators
highlighting module code... [ 89%] datumaro.util
highlighting module code... [ 90%] datumaro.util.annotation_util
highlighting module code... [ 91%] datumaro.util.attrs_util
highlighting module code... [ 92%] datumaro.util.image
highlighting module code... [ 93%] datumaro.util.image_cache
highlighting module code... [ 94%] datumaro.util.log_utils
highlighting module code... [ 95%] datumaro.util.mask_tools
highlighting module code... [ 96%] datumaro.util.os_util
highlighting module code... [ 97%] datumaro.util.scope
highlighting module code... [ 98%] datumaro.util.telemetry_stub
highlighting module code... [ 99%] datumaro.util.telemetry_utils
highlighting module code... [100%] datumaro.util.tf_util

writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 35 warnings.

The HTML pages are in build/html.
cp source/_static/redirects/guide-homepage-redirect.html "build"/html/index.html
